// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// ITaskController is an autogenerated mock type for the ITaskController type
type ITaskController struct {
	mock.Mock
}

// CreateTask provides a mock function with given fields: c
func (_m *ITaskController) CreateTask(c *gin.Context) {
	_m.Called(c)
}

// DeleteTask provides a mock function with given fields: c
func (_m *ITaskController) DeleteTask(c *gin.Context) {
	_m.Called(c)
}

// GetTaskByID provides a mock function with given fields: c
func (_m *ITaskController) GetTaskByID(c *gin.Context) {
	_m.Called(c)
}

// GetUserTasks provides a mock function with given fields: c
func (_m *ITaskController) GetUserTasks(c *gin.Context) {
	_m.Called(c)
}

// UpdateTask provides a mock function with given fields: c
func (_m *ITaskController) UpdateTask(c *gin.Context) {
	_m.Called(c)
}

// NewITaskController creates a new instance of ITaskController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewITaskController(t interface {
	mock.TestingT
	Cleanup(func())
}) *ITaskController {
	mock := &ITaskController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
