// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// IUserController is an autogenerated mock type for the IUserController type
type IUserController struct {
	mock.Mock
}

// Login provides a mock function with given fields: c
func (_m *IUserController) Login(c *gin.Context) {
	_m.Called(c)
}

// Promote provides a mock function with given fields: c
func (_m *IUserController) Promote(c *gin.Context) {
	_m.Called(c)
}

// Register provides a mock function with given fields: c
func (_m *IUserController) Register(c *gin.Context) {
	_m.Called(c)
}

// NewIUserController creates a new instance of IUserController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIUserController(t interface {
	mock.TestingT
	Cleanup(func())
}) *IUserController {
	mock := &IUserController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
