name: Go CI and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Check out the code
    - name: Check out code
      uses: actions/checkout@v4

    # Step 2: Set up the Go environment
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21' 

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: go mod tidy

    # Step 4: Run Unit Tests
    - name: Run Unit Tests
      run: go test ./... -v -cover
    - name: Lint Go Code
      run: |
        go install golang.org/x/lint/golint@latest
        golint -set_exit_status $(go list ./...)
    - name: Check Formatting
      run: test -z $(gofmt -l .)